---
- name: install curl
  apt:
    name:
      - curl
    cache_valid_time: 86400  # 24h

- name: install k3s
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_KUBECONFIG_MODE=640 sh -
  args:
    creates: /usr/local/bin/k3s

- file:
    path: /etc/rancher/k3s/k3s.yaml
    group: vagrant

# kube config

- file:
    path: /root/.kube
    mode: 0755
    owner: root
    group: root
    state: directory

- name: write kube config for root
  shell: |
    k3s kubectl config view --raw > /root/.kube/config
  args:
    creates: /root/.kube/config

- file:
    path: /root/.kube/config
    mode: 0600
    owner: root
    group: root

- file:
    path: /home/vagrant/.kube
    mode: 0755
    owner: vagrant
    group: vagrant
    state: directory

- name: write kube config for vagrant
  shell: |
    k3s kubectl config view --raw > /home/vagrant/.kube/config
  args:
    creates: /home/vagrant/.kube/config

- file:
    path: /home/vagrant/.kube/config
    mode: 0600
    owner: vagrant
    group: vagrant

- file:
    path: ~/.kube
    mode: 0755
    state: directory
  delegate_to: localhost

- name: copy kube config to localhost
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
    flat: true
