---
- name: install stern
  shell: |
    curl -sfL https://github.com/stern/stern/releases/download/v{{ stern_version }}/stern_{{ stern_version }}_linux_amd64.tar.gz | tar zxf - -C /usr/local/bin
  args:
    creates: /usr/local/bin/stern
