---
- name: install apt-transport-https
  apt: name=apt-transport-https

- name: add apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: add apt repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
  register: result

- name: apt update
  apt: update_cache=yes
  when: result|changed
