---
- apt:
    name: "{{ item }}"
    cache_valid_time: 86400  # 24h
  with_items:
    - libseccomp2

- file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/cni/bin
    - /etc/cni/net.d

- unarchive:
    src: "https://storage.googleapis.com/cri-containerd-release/cri-containerd-{{ containerd_version }}.linux-amd64.tar.gz"
    dest: /
    remote_src: true

- service:
    name: containerd
    enabled: true
    state: started
